version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: v20.10.0
  pre_build:
    commands:
      - echo Build started on `date`
      - npm install
  build:
    commands:
      - echo Build Not Required
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
